### ISSUE TITLE
Slightly confused over script - testing py2 & 3

### ISSUE THREAD

**Issue by ghost** [kmarchand/ulysses-markdown-export#1]
Hi
I realize this is a very old script but the concept is what I'm looking for to make sure I'm not locked into the Ulysses ecosystem.

I'm learning Python right now so the script makes some sense except when it gets to this part:

`ufiles.remove(ufiles[0])`

When I test this variable before the main function it's empty which makes sense, it's being removed. Can you help me understand how to make this work, would really appreciate any help. Script runs but as I mentioned, no output as the variable and index is now zeroed!

thanks for the script!

**Comment by kmarchand** [comment]
Hey!  Holy smokes it's been a long time since I posted this.

I haven't used Ulysses for a long time but I just installed it to test and if you drag a sheet out to the desktop it exports in their own ".ulyz" encoded format and not whatever it did before when I used this script so this won't work at all (this wasn't decoding any custom encoded format or anything, just shuffling files and file names around I think).

However, it looks like there's better build-in export than before so that should cover you (right click on the sheets and choose quick-export, change type from PDF to text, then you can chose markdown or other stuff).

I can't remember why I did this script the way it is (I was just learning python at the time too so I wouldn't recommend referring to this thing since it's probably a mess) but what looks like it does is add the file names found in the source file directory ("udir") to the list called "ufiles", and then for some reason just removes the first entry on that list (index "[0]") - probably because it was not an actual sheet and was an extra thing Ulysses exported, I'm not sure.

```
> ufiles = [1,2,3,4,5]
> ufiles
[1, 2, 3, 4, 5]
> ufiles.remove(ufiles[0])
> ufiles
[2, 3, 4, 5]
```

I'm actually just finishing up a much more elaborate script to normalize markdown files exported from Craft to clean them up for import into Obsidian which I'm using now (and which is fantastic).  I'm going to post that here at some point soon if you're interested.

**Comment by ghost** [comment]
Hey there!

Thanks for taking time to discuss the piece of code from the archives. 

Thanks for the tip about the Quick export… just tested that and it works great for single files but if you select hundreds it saves them all as one big MD file… it should make it easier to split them I guess but it’s almost like they’re trying to keep you paying 😀

Appreciate you looking at this script. Would be great to see what you’re doing with the Markdown script for sure. 

Thanks again!
